version: "3.8"

services:

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "0.0.0.0:1884:1884"
    container_name: mosquitto
    hostname: mosquitto
    volumes:
      - "./conf:/mosquitto/config"
